name: Deploy to Localhost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Sync files
        run: |
          lftp -e "
          open -u ${FTP_USERNAME},${FTP_PASSWORD} ${FTP_HOST}
          mirror --reverse --verbose --exclude-glob=wp-content/uploads ./wp-content ${FTP_DIR}/wp-content
          bye
          "
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_DIR: ${{ secrets.FTP_DIR }}
